### ISSUE TITLE
'PIN_MAP' was not declared in this scope

### ISSUE THREAD

**Issue by ZhiHaoSun** [ScruffR/Adafruit_HX8357#1]
Veryfing code using this library in Particle Build fails with this error:

```

```

**Comment by ScruffR** [comment]
It's a known issue which will be solved once Particle firmware 0.4.2 will be released to Particle Build.

**Comment by ScruffR** [comment]
Long time but it's now sorted.
It's now compatible with Core FW versions 0.3.4ff and Photon 0.4.1ff and P1 0.4.3ff (and hopefully Electron too ;-) )
