### ISSUE TITLE
Feature request: option to use SPI1 on Photon

### ISSUE THREAD

**Issue by TheMadTexan42** [ScruffR/Adafruit_HX8357#3]
Would love to have the option of using the SPI1 interface on the Photon, rather than the standard SPI.  This is primarily to support applications that either need to use both SPI interfaces (and for whatever reason the display should be on SPI1), or applications that need to free up the analog ports consumed by the SPI interface.

**Comment by ScruffR** [comment]
Now (v0.9.7) there is a new overload
```
Adafruit_HX8357(SPIClass& _SPI, int8_t _CS, int8_t _DC, int8_t _RST);
```
Which takes an SPIClass reference as first parameter.

**Comment by TheMadTexan42** [comment]
AWESOME!!!!!
